"""
Markdown export utility for WorldBuilder projects.
"""

from models.project import Project
from constants import ALL_ELEMENT_NAMES
from datetime import datetime


def generate_markdown(project: Project) -> str:
    """
    프로젝트를 Markdown 문서로 변환합니다.

    Args:
        project: 변환할 프로젝트

    Returns:
        Markdown 형식의 문자열
    """
    sections = []

    # 제목 및 메타데이터
    sections.append(f"# {project.project_name}")
    sections.append("")
    sections.append(f"**장르**: {project.genre}")
    sections.append(f"**완성도**: {project.completion_rate * 100:.1f}%")
    sections.append(f"**최종 수정일**: {project.updated_at}")
    sections.append("")
    sections.append("---")
    sections.append("")

    # 컨셉
    sections.append("## 💡 컨셉")
    sections.append("")

    if project.concept.logline:
        sections.append("### 로그라인")
        sections.append("")
        sections.append(f"> {project.concept.logline}")
        sections.append("")

    if project.concept.keywords:
        sections.append("### 키워드")
        sections.append("")
        keywords_str = ", ".join([f"`{kw}`" for kw in project.concept.keywords])
        sections.append(keywords_str)
        sections.append("")

    sections.append("---")
    sections.append("")

    # 12요소
    sections.append("## 🌍 12요소")
    sections.append("")

    # 요소 라벨 매핑
    element_labels = {
        'space': '🌌 공간',
        'time': '⏰ 시간',
        'creatures': '👥 생물',
        'nature': '🌿 자연',
        'culture': '🎭 문화',
        'language': '🗣️ 언어',
        'mythology': '⚡ 신화',
        'philosophy': '💭 철학',
        'rules': '⚖️ 규칙',
        'economy': '💰 경제',
        'politics': '🏛️ 정치',
        'energy': '✨ 에너지'
    }

    for element_name in ALL_ELEMENT_NAMES:
        label = element_labels.get(element_name, element_name)
        sections.append(f"### {label}")
        sections.append("")

        if element_name == 'rules':
            # 규칙은 특수 처리
            rules = project.elements.rules

            if rules.natural:
                sections.append("**자연법칙**:")
                sections.append("")
                for rule in rules.natural:
                    sections.append(f"- {rule}")
                sections.append("")

            if rules.social:
                sections.append("**사회규범**:")
                sections.append("")
                for rule in rules.social:
                    sections.append(f"- {rule}")
                sections.append("")

            if rules.religious:
                sections.append("**종교법**:")
                sections.append("")
                for rule in rules.religious:
                    sections.append(f"- {rule}")
                sections.append("")

            if not (rules.natural or rules.social or rules.religious):
                sections.append("_작성되지 않음_")
                sections.append("")

        else:
            # 일반 요소
            element = getattr(project.elements, element_name)
            if element.description and element.description.strip():
                sections.append(element.description)
                sections.append("")
            else:
                sections.append("_작성되지 않음_")
                sections.append("")

    # 연결 관계 (있는 경우)
    if project.connections:
        sections.append("---")
        sections.append("")
        sections.append("## 🔗 연결 관계")
        sections.append("")
        for i, conn in enumerate(project.connections, 1):
            sections.append(f"{i}. {conn}")
            sections.append("")

    # 노트 (있는 경우)
    if project.notes and project.notes.strip():
        sections.append("---")
        sections.append("")
        sections.append("## 📝 노트")
        sections.append("")
        sections.append(project.notes)
        sections.append("")

    # 푸터
    sections.append("---")
    sections.append("")
    sections.append(f"_Generated by WorldBuilder on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_")

    return "\n".join(sections)


def get_filename(project: Project) -> str:
    """
    프로젝트에 맞는 파일명을 생성합니다.

    Args:
        project: 프로젝트

    Returns:
        안전한 파일명 (확장자 포함)
    """
    # 프로젝트 이름에서 파일명으로 사용할 수 없는 문자 제거
    safe_name = project.project_name
    invalid_chars = '<>:"/\\|?*'
    for char in invalid_chars:
        safe_name = safe_name.replace(char, '_')

    # 공백을 언더스코어로 변경
    safe_name = safe_name.replace(' ', '_')

    return f"{safe_name}.md"
